### ISSUE TITLE
Logitech G PRO Superlight missing

### ISSUE THREAD

**Issue by CyanBook** [libratbag/libratbag#1119]
**Is your feature request related to a problem? Please describe.**
the Logitech G PRO Superlight mouse is missing. Can you add that?

**Describe the solution you'd like**
Add the mouse to the supported ones.

**Comment by FFY00** [comment]
I opened #1122 which should fix this.

I also sent patches adding support for the receiver to the kernel driver.

https://www.spinics.net/lists/linux-input/msg71493.html
https://www.spinics.net/lists/linux-input/msg71495.html

They have not been merged yet, I am not sure in which Linux version this will be fixed. In the meantime, the PR still allows to configure the device via the USB connection, just not the receiver, which needs the kernel changes.

cc @brianegan

**Comment by seantcanavan** [comment]
Is basic functionality for the superlight supported in general however now that #1122 is merged? It seems like the core issue for the kernel is related to using the mouse with the powerplay mat.

**Comment by FFY00** [comment]
My first patch, which fixed support for the Powerplay mat, was merged, my second one, which added support for the new Lightspeed receiver that comes with the G Pro Wireless Superlight, wasn't.

Currently, with #1122:
  - device connected via USB: can be configured by libratbag
  - device connected via Powerplay receiver: can be configured by libratbag
  - device connected via Lightspeed receiver that comes with the device: **cannot be configured** by libratbag (missing kernel support)

I should fix up the patch that adds support for the new Lightspeed receiver and re-submit, but haven't had that much time.

**Comment by GloriousEggroll** [comment]
I compiled the kernel with your patches @FFY00 but unfortunately it's still not showing up in ratbagctl output nor the piper gui. Is there anything additional needed on the ratbag or piper ends to work with the kernel patches?

**Comment by berglh** [comment]
Having the same issue as @GloriousEggroll. Running libratbag 0.16 and piper 0.6 on 5.15.6-051506-generic and I'm not able to configure this by the Lightspeed receiver. @FFY00 is there a working kernel version for this now?

**Comment by idle5** [comment]
Any updates to this? Would really appreciate if anyone could get this to work with the receiver. Would be happy to provide any information from the terminal. Thanks in advance!

**Comment by berglh** [comment]
@FFY00 I just wanted to add to this, I can see the patch for the kernel for 5.11-upstream was added. I'm running kernel 5.15.6 and I can see in the source tree that the changes for kernel are there: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/hid/hid-logitech-dj.c?h=v5.15.6
I guess this was required for the receiver to work at all?

So, if the lightspeed connector patch has been added, then my guess is that libratbag 0.16 should be working with the Lightspeed connector if that's all that was required. However, as @GloriousEggroll pointed out, that it's still not working. Looking at the libratbagd #1122 PR, I can see that it's added a device, but I can't see the Lightspeed connector added here. My `lsbusb` output for my receiver is as follows:

```
Bus 001 Device 009: ID 046d:c547 Logitech, Inc. USB Receiver
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x046d Logitech, Inc.
  idProduct          0xc547 
  bcdDevice            4.00
  iManufacturer           1 Logitech
  iProduct                2 USB Receiver
  iSerial                 0 
  bNumConfigurations      1
```
Do we simply need to add the the ID into the device files in libratbagd?
```diff
[Device]
Name=Logitech G Pro X Wireless Superlight
- DeviceMatch=usb:046d:4093;usb:046d:c094
+ DeviceMatch=usb:046d:4093;usb:046d:c094;usb:046d:c547
LedTypes=logo;battery;dpi;
Driver=hidpp20
```

**Comment by berglh** [comment]
I've tried building the HID driver with the attached patch applied to my current kernel version (v5.15.6) from Ubuntu mainline repo (git://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack) branch (cod/mainline/v5.15.6). I plopped the built driver files in `/lib/modules/5.15.6-051506-generic/kernel/drivers/hid/` and did an `update-initramfs -u` to rebuild the initramfs image, rebooted and still not working for me with piper.

To be fair, I don't really know what I'm doing, if this is the correct procedure or not. I modified the diff as per @bentiss comment on https://www.spinics.net/lists/linux-input/msg75936.html for this PR.
> I've been pinged last week about the G Pro X superlight, and Peter found
> that this patch never got into upstream.
> AFAICT, compared to upstream the following code change should have the
> same effect that what you proposed here:
> ... [ more or less the diff below ]
> Would you mind sending a v2 of the patch updated to the current for-next so we can schedule this for 5.17?
> Cheers,
> Benjamin

[logitech.patch](https://github.com/libratbag/libratbag/files/8551241/logitech.patch.txt)
```diff
diff --git a/drivers/hid/hid-ids.h b/drivers/hid/hid-ids.h
index 3706c635b..9f36ba221 100644
--- a/drivers/hid/hid-ids.h
+++ b/drivers/hid/hid-ids.h
@@ -816,6 +816,7 @@
 #define USB_DEVICE_ID_LOGITECH_NANO_RECEIVER_2		0xc534
 #define USB_DEVICE_ID_LOGITECH_NANO_RECEIVER_LIGHTSPEED_1	0xc539
 #define USB_DEVICE_ID_LOGITECH_NANO_RECEIVER_LIGHTSPEED_1_1	0xc53f
+#define USB_DEVICE_ID_LOGITECH_NANO_RECEIVER_LIGHTSPEED_1_2 0xc547
 #define USB_DEVICE_ID_LOGITECH_NANO_RECEIVER_POWERPLAY	0xc53a
 #define USB_DEVICE_ID_SPACETRAVELLER	0xc623
 #define USB_DEVICE_ID_SPACENAVIGATOR	0xc626
diff --git a/drivers/hid/hid-logitech-dj.c b/drivers/hid/hid-logitech-dj.c
index a0017b010..b0667789b 100644
--- a/drivers/hid/hid-logitech-dj.c
+++ b/drivers/hid/hid-logitech-dj.c
@@ -1691,11 +1691,12 @@ static int logi_dj_raw_event(struct hid_device *hdev,
 		}
 		/*
 		* Mouse-only receivers send unnumbered mouse data. The 27 MHz
-		* receiver uses 6 byte packets, the nano receiver 8 bytes.
+		* receiver uses 6 byte packets, the nano receiver 8 bytes and
+		* some gaming ones are using 16 bytes.
 		*/
 		if (djrcv_dev->unnumbered_application == HID_GD_MOUSE &&
-		   size <= 8) {
-			u8 mouse_report[9];
+		   size <= 16) {
+			u8 mouse_report[17];
 
 			/* Prepend report id */
 			mouse_report[0] = REPORT_TYPE_MOUSE;
@@ -1979,6 +1980,10 @@ static const struct hid_device_id logi_dj_receivers[] = {
 	 HID_USB_DEVICE(USB_VENDOR_ID_LOGITECH,
 		USB_DEVICE_ID_LOGITECH_NANO_RECEIVER_LIGHTSPEED_1_1),
 	.driver_data = recvr_type_gaming_hidpp},
+	{ /* Logitech lightspeed receiver (0xc547) */
+	 HID_USB_DEVICE(USB_VENDOR_ID_LOGITECH,
+		USB_DEVICE_ID_LOGITECH_NANO_RECEIVER_LIGHTSPEED_1_2),
+	.driver_data = recvr_type_gaming_hidpp},
 
 	{ /* Logitech 27 MHz HID++ 1.0 receiver (0xc513) */
 	 HID_USB_DEVICE(USB_VENDOR_ID_LOGITECH, USB_DEVICE_ID_MX3000_RECEIVER),
```

**Comment by CyanBook** [comment]
So where's the problem exactly? I'm not familiar with either kernels or drivers. If there's something I can do to help, please let me know.

**Comment by KyleGospo** [comment]
If you're on Fedora I've set up a COPR repo with a dkms kernel module that applies that patch. Can confirm libratbag works for me with a Superlight+Powerplay combo.

https://copr.fedorainfracloud.org/coprs/kylegospo/kmod-hid-logitech-dj-dkms/

Shouldn't be too hard to compile this for other distros until this patch is upstreamed.

**Comment by berglh** [comment]
@KyleGospo That's pretty sweet, did it work with the receiver that comes with the mouse? I'm not sure how the powerplay works, but I seem to remember it was a wireless charging mat with a receiver built in. I'll give this a burl on Ewbuntu.

**Comment by KyleGospo** [comment]
@berglh It's worked for me with the dongle it came with since at least Linux 5.15, this patch only deals with the Powerplay mat AFAIK

**Comment by berglh** [comment]
@KyleGospo Yeah, I'm not sure. I'm running on 5.17.5, libratbag 0.16-1+git1825 and piper 0.6+git485. There might be still something to my receiver not being classified properly, you can see it is being detected on dmesg below.

```bash
[    1.873419] usb 7-3: Manufacturer: Logitech
[    1.924854] input: Logitech USB Receiver as /devices/pci0000:00/0000:00:08.1/0000:08:00.3/usb7/7-3/7-3:1.0/0003:046D:C547.0003/input/input2
[    1.924893] hid-generic 0003:046D:C547.0003: input,hidraw2: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-0000:08:00.3-3/input0
[    1.924966] input: Logitech USB Receiver Keyboard as /devices/pci0000:00/0000:00:08.1/0000:08:00.3/usb7/7-3/7-3:1.1/0003:046D:C547.0004/input/input3
[    1.983358] hid-generic 0003:046D:C547.0004: input,hidraw3: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-0000:08:00.3-3/input1
[    1.983426] hid-generic 0003:046D:C547.0005: hiddev2,hidraw4: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:08:00.3-3/input2
```

**Comment by KyleGospo** [comment]
It worked OOTB with the included dongle, but if it synced with the Powerplay mat it was a headache to fix.

**Comment by berglh** [comment]
@KyleGospo So you could talk to it via ratbagctl and configure it with piper OOTB with the receiver in the box? 

Let me clear things up, I can use the mouse just fine, but I can't configure any of the DPI settings unless I plug the mouse into the USB port directly.  Interestingly, I have the old Logitech G Pro Wireless, and the Superlight doesn't seem to work with it's dongle, but I didn't look in-depth into how the mouse is paired to a particular dongle - this might be a workaround if I can figure that out.  The old mouse had a DPI profile button I could cycle through, but this new one doesn't, it's a hassle to plug it in each time I want to adjust the DPI (which is pretty frequently).  Powerplay mat could be an option I guess.
